enyo.depends(
    "source/scenes.js",
    "source/canvas.js",
    "source/StatefulCheckBox.js",
    "source/SnowfallSettings.js",
	"source/Snowfall.js",
    "source/SnowfallWithMenu.js",
    "source/SnowfallLauncher.js",
	"source/Snowfall.css"
);
