window.scenes = [ {
        image: 'images/scenes/blank.png',
        thumbnail: 'images/scenes/blank-thumb.png',
        scenetype: 'dark'
//        ,lines: [
//            { x1: -100, y1: 735, x2: 1024, y2: 735 }
//        ]
    }, {
        image: 'images/scenes/fence.jpg',
        thumbnail: 'images/scenes/fence-thumb.jpg',
        scenetype: 'light'
    }, {
        image: 'images/scenes/grass-dark.jpg',
        thumbnail: 'images/scenes/grass-dark-thumb.jpg',
        scenetype: 'dark'
    }, {
        image: 'images/scenes/night.jpg',
        thumbnail: 'images/scenes/night-thumb.jpg',
        scenetype: 'dark'
    }, {
        image: 'images/scenes/parkbench.jpg',
        thumbnail: 'images/scenes/parkbench-thumb.jpg',
        scenetype: 'dark'
    }, {
        image: 'images/scenes/road.jpg',
        thumbnail: 'images/scenes/road-thumb.jpg',
        scenetype: 'light'
    }, {
        image: 'images/scenes/toyvillage.jpg',
        thumbnail: 'images/scenes/toyvillage-thumb.jpg',
        scenetype: 'dark'
    }, {
        image: 'images/scenes/trees.jpg',
        thumbnail: 'images/scenes/trees-thumb.jpg',
        scenetype: 'light'
    }, {
        image: 'images/scenes/snowman.png',
        thumbnail: 'images/scenes/snowman-thumb.png',
        scenetype: 'dark'
    }, {
        image: 'images/scenes/snowflakes.png',
        thumbnail: 'images/scenes/snowflakes-thumb.png',
        scenetype: 'dark'
    }, {
        image: 'images/scenes/evergreens.png',
        thumbnail: 'images/scenes/evergreens-thumb.png',
        scenetype: 'light'
    }, {
        image: 'images/scenes/snowglobe.png',
        thumbnail: 'images/scenes/snowglobe-thumb.png',
        scenetype: 'light'
    }, {
        image: 'images/scenes/treefrost.png',
        thumbnail: 'images/scenes/treefrost-thumb.png',
        scenetype: 'light'
    }, {
        image: 'images/scenes/white_tree.png',
        thumbnail: 'images/scenes/white_tree-thumb.png',
        scenetype: 'light'
    }, {
        image: 'images/scenes/colorfultrees.png',
        thumbnail: 'images/scenes/colorfultrees-thumb.png',
        scenetype: 'light'
    }
];
